export const countries = [
  { name: "Afghanistan", path: require("../worldFlags/Afghanistan.png") },
  { name: "Albania", path: require("../worldFlags/Albania.png") },
  { name: "Algeria", path: require("../worldFlags/Algeria.png") },
  { name: "Andorra", path: require("../worldFlags/Andorra.png") },
 { name: "Angola", path: require("../worldFlags/Angola.png") },
  { name: "Anguilla", path: require("../worldFlags/Anguilla.png") },
  //{ name: "Antarctica", path: require("../worldFlags/Antarctica.png") },
  { name: "Antigua and Barbuda", path: require("../worldFlags/Antigua_and_Barbuda.png") },
  { name: "Argentina", path: require("../worldFlags/Argentina.png") },
  { name: "Armenia", path: require("../worldFlags/Armenia.png") },
  //{ name: "Aruba", path: require("../worldFlags/Aruba.png") },
  { name: "Australia", path: require("../worldFlags/Australia.png") },
  { name: "Austria", path: require("../worldFlags/Austria.png") },
  { name: "Azerbaijan", path: require("../worldFlags/Azerbaijan.png") },
  { name: "Bahamas", path: require("../worldFlags/Bahamas.png") },
  { name: "Bahrain", path: require("../worldFlags/Bahrain.png") },
  { name: "Bangladesh", path: require("../worldFlags/Bangladesh.png") },
  { name: "Barbados", path: require("../worldFlags/Barbados.png") },
  { name: "Belarus", path: require("../worldFlags/Belarus.png") },
  { name: "Belgium", path: require("../worldFlags/Belgium.png") },
  { name: "Belize", path: require("../worldFlags/Belize.png") },
  { name: "Benin", path: require("../worldFlags/Benin.png") },
  { name: "Bhutan", path: require("../worldFlags/Bhutan.png") },
  { name: "Bolivia", path: require("../worldFlags/Bolivia.png") },
  { name: "Bosnia and Herzegovina", path: require("../worldFlags/Bosnia_and_Herzegovina.png") },
  { name: "Botswana", path: require("../worldFlags/Botswana.png") },
  { name: "Brazil", path: require("../worldFlags/Brazil.png") },
  { name: "Brunei", path: require("../worldFlags/Brunei.png") },
  { name: "Bulgaria", path: require("../worldFlags/Bulgaria.png") },
  { name: "Burkina Faso", path: require("../worldFlags/Burkina_Faso.png") },
  { name: "Burundi", path: require("../worldFlags/Burundi.png") },
 // { name: "Cabo Verde", path: require("../worldFlags/Cabo_Verde.png") },
  { name: "Cambodia", path: require("../worldFlags/Cambodia.png") },
  { name: "Cameroon", path: require("../worldFlags/Cameroon.png") },
  { name: "Canada", path: require("../worldFlags/Canada.png") },
  { name: "Cape Verde", path: require("../worldFlags/Cape_Verde.png") },
  { name: "Central African Republic", path: require("../worldFlags/Central_African_Republic.png") },
  { name: "Chad", path: require("../worldFlags/Chad.png") },
  { name: "Chile", path: require("../worldFlags/Chile.png") },
  { name: "China", path: require("../worldFlags/China.png") },
  { name: "Colombia", path: require("../worldFlags/Colombia.png") },
  { name: "Comoros", path: require("../worldFlags/Comoros.png") },
//  { name: "Congo (Brazzaville)", path: require("../worldFlags/Congo_Brazzaville.png") },
//  { name: "Congo (Kinshasa)", path: require("../worldFlags/Congo_Kinshasa.png") },
  { name: "Costa Rica", path: require("../worldFlags/Costa_Rica.png") },
  { name: "Croatia", path: require("../worldFlags/Croatia.png") },
  { name: "Cuba", path: require("../worldFlags/Cuba.png") },
  { name: "Cyprus", path: require("../worldFlags/Cyprus.png") },
  { name: "Czech Republic", path: require("../worldFlags/Czech_Republic.png") },
  { name: "Denmark", path: require("../worldFlags/Denmark.png") },
  { name: "Djibouti", path: require("../worldFlags/Djibouti.png") },
  { name: "Dominica", path: require("../worldFlags/Dominica.png") },
  { name: "Dominican Republic", path: require("../worldFlags/Dominican_Republic.png") },
  { name: "East Timor", path: require("../worldFlags/East_Timor.png") },
  { name: "Ecuador", path: require("../worldFlags/Ecuador.png") },
  { name: "Egypt", path: require("../worldFlags/Egypt.png") },
  { name: "El Salvador", path: require("../worldFlags/El_Salvador.png") },
  { name: "Equatorial Guinea", path: require("../worldFlags/Equatorial_Guinea.png") },
  { name: "Eritrea", path: require("../worldFlags/Eritrea.png") },
  { name: "Estonia", path: require("../worldFlags/Estonia.png") },
  { name: "Ethiopia", path: require("../worldFlags/Ethiopia.png") },
  { name: "Fiji", path: require("../worldFlags/Fiji.png") },
  { name: "Finland", path: require("../worldFlags/Finland.png") },
  { name: "France", path: require("../worldFlags/France.png") },
  { name: "Gabon", path: require("../worldFlags/Gabon.png") },
 // { name: "Gambia, The", path: require("../worldFlags/Gambia.png") },
  { name: "Georgia", path: require("../worldFlags/Georgia.png") },
  { name: "Germany", path: require("../worldFlags/Germany.png") },
  { name: "Ghana", path: require("../worldFlags/Ghana.png") },
  { name: "Greece", path: require("../worldFlags/Greece.png") },
  { name: "Grenada", path: require("../worldFlags/Grenada.png") },
  { name: "Guatemala", path: require("../worldFlags/Guatemala.png") },
  { name: "Guinea", path: require("../worldFlags/Guinea.png") },
  { name: "Guinea-Bissau", path: require("../worldFlags/Guinea-Bissau.png") },
  { name: "Guyana", path: require("../worldFlags/Guyana.png") },
  { name: "Haiti", path: require("../worldFlags/Haiti.png") },
  { name: "Honduras", path: require("../worldFlags/Honduras.png") },
  { name: "Hungary", path: require("../worldFlags/Hungary.png") },
  { name: "Iceland", path: require("../worldFlags/Iceland.png") },
  { name: "India", path: require("../worldFlags/India.png") },
  { name: "Indonesia", path: require("../worldFlags/Indonesia.png") },
  { name: "Iran", path: require("../worldFlags/Iran.png") },
  { name: "Iraq", path: require("../worldFlags/Iraq.png") },
  { name: "Ireland", path: require("../worldFlags/Ireland.png") },
  { name: "Israel", path: require("../worldFlags/Israel.png") },
  { name: "Italy", path: require("../worldFlags/Italy.png") },
  { name: "Ivory Coast", path: require("../worldFlags/Ivory_Coast.png") },
  { name: "Jamaica", path: require("../worldFlags/Jamaica.png") },
  { name: "Japan", path: require("../worldFlags/Japan.png") },
  { name: "Jordan", path: require("../worldFlags/Jordan.png") },
  { name: "Kazakhstan", path: require("../worldFlags/Kazakhstan.png") },
  { name: "Kenya", path: require("../worldFlags/Kenya.png") },
  { name: "Kiribati", path: require("../worldFlags/Kiribati.png") },
 // { name: "North Korea", path: require("../worldFlags/North_Korea.png") },
//  { name: "South Korea", path: require("../worldFlags/South_Korea.png") },
  { name: "Kosovo", path: require("../worldFlags/Kosovo.png") },
  { name: "Kuwait", path: require("../worldFlags/Kuwait.png") },
  { name: "Kyrgyzstan", path: require("../worldFlags/Kyrgyzstan.png") },
  { name: "Laos", path: require("../worldFlags/Laos.png") },
  { name: "Latvia", path: require("../worldFlags/Latvia.png") },
  { name: "Lebanon", path: require("../worldFlags/Lebanon.png") },
  { name: "Lesotho", path: require("../worldFlags/Lesotho.png") },
  { name: "Liberia", path: require("../worldFlags/Liberia.png") },
  { name: "Libya", path: require("../worldFlags/Libya.png") },
  { name: "Liechtenstein", path: require("../worldFlags/Liechtenstein.png") },
  { name: "Lithuania", path: require("../worldFlags/Lithuania.png") },
  { name: "Luxembourg", path: require("../worldFlags/Luxembourg.png") },
 // { name: "North Macedonia", path: require("../worldFlags/North_Macedonia.png") },
  { name: "Madagascar", path: require("../worldFlags/Madagascar.png") },
  { name: "Malawi", path: require("../worldFlags/Malawi.png") },
  { name: "Malaysia", path: require("../worldFlags/Malaysia.png") },
  { name: "Maldives", path: require("../worldFlags/Maldives.png") },
  { name: "Mali", path: require("../worldFlags/Mali.png") },
  { name: "Malta", path: require("../worldFlags/Malta.png") },
  { name: "Marshall Islands", path: require("../worldFlags/Marshall_Islands.png") },
  { name: "Mauritania", path: require("../worldFlags/Mauritania.png") },
  { name: "Mauritius", path: require("../worldFlags/Mauritius.png") },
  { name: "Mexico", path: require("../worldFlags/Mexico.png") },
  { name: "Micronesia", path: require("../worldFlags/Micronesia.png") },
  { name: "Moldova", path: require("../worldFlags/Moldova.png") },
  { name: "Monaco", path: require("../worldFlags/Monaco.png") },
  { name: "Mongolia", path: require("../worldFlags/Mongolia.png") },
  { name: "Montenegro", path: require("../worldFlags/Montenegro.png") },
  { name: "Morocco", path: require("../worldFlags/Morocco.png") },
  { name: "Mozambique", path: require("../worldFlags/Mozambique.png") },
//  { name: "Myanmar", path: require("../worldFlags/Myanmar.png") },
  { name: "Namibia", path: require("../worldFlags/Namibia.png") },
  { name: "Nauru", path: require("../worldFlags/Nauru.png") },
  { name: "Nepal", path: require("../worldFlags/Nepal.png") },
  { name: "Netherlands", path: require("../worldFlags/Netherlands.png") },
  { name: "New Zealand", path: require("../worldFlags/New_Zealand.png") },
  { name: "Nicaragua", path: require("../worldFlags/Nicaragua.png") },
  { name: "Niger", path: require("../worldFlags/Niger.png") },
  { name: "Nigeria", path: require("../worldFlags/Nigeria.png") },
  { name: "Norway", path: require("../worldFlags/Norway.png") },
  { name: "Oman", path: require("../worldFlags/Oman.png") },
  { name: "Pakistan", path: require("../worldFlags/Pakistan.png") },
  { name: "Palau", path: require("../worldFlags/Palau.png") },
  { name: "Panama", path: require("../worldFlags/Panama.png") },
  { name: "Papua New Guinea", path: require("../worldFlags/Papua_New_Guinea.png") },
  { name: "Paraguay", path: require("../worldFlags/Paraguay.png") },
  { name: "Peru", path: require("../worldFlags/Peru.png") },
  { name: "Philippines", path: require("../worldFlags/Philippines.png") },
  { name: "Poland", path: require("../worldFlags/Poland.png") },
  { name: "Portugal", path: require("../worldFlags/Portugal.png") },
  { name: "Qatar", path: require("../worldFlags/Qatar.png") },
  { name: "Romania", path: require("../worldFlags/Romania.png") },
  { name: "Russia", path: require("../worldFlags/Russia.png") },
  { name: "Rwanda", path: require("../worldFlags/Rwanda.png") },
  { name: "Saint Kitts and Nevis", path: require("../worldFlags/Saint_Kitts_and_Nevis.png") },
  { name: "Saint Lucia", path: require("../worldFlags/Saint_Lucia.png") },
  { name: "Saint Vincent and the Grenadines", path: require("../worldFlags/Saint_Vincent_and_the_Grenadines.png") },
  { name: "Samoa", path: require("../worldFlags/Samoa.png") },
  { name: "San Marino", path: require("../worldFlags/San_Marino.png") },
  { name: "Sao Tome and Principe", path: require("../worldFlags/Sao_Tome_and_Principe.png") },
  { name: "Saudi Arabia", path: require("../worldFlags/Saudi_Arabia.png") },
  { name: "Senegal", path: require("../worldFlags/Senegal.png") },
  { name: "Serbia", path: require("../worldFlags/Serbia.png") },
  { name: "Seychelles", path: require("../worldFlags/Seychelles.png") },
  { name: "Sierra Leone", path: require("../worldFlags/Sierra_Leone.png") },
  { name: "Singapore", path: require("../worldFlags/Singapore.png") },
  { name: "Slovakia", path: require("../worldFlags/Slovakia.png") },
  { name: "Slovenia", path: require("../worldFlags/Slovenia.png") },
  { name: "Solomon Islands", path: require("../worldFlags/Solomon_Islands.png") },
  { name: "Somalia", path: require("../worldFlags/Somalia.png") },
  { name: "South Africa", path: require("../worldFlags/South_Africa.png") },
  { name: "South Sudan", path: require("../worldFlags/South_Sudan.png") },
  { name: "Spain", path: require("../worldFlags/Spain.png") },
  { name: "Sri Lanka", path: require("../worldFlags/Sri_Lanka.png") },
  { name: "Sudan", path: require("../worldFlags/Sudan.png") },
  { name: "Suriname", path: require("../worldFlags/Suriname.png") },
  { name: "Sweden", path: require("../worldFlags/Sweden.png") },
  { name: "Switzerland", path: require("../worldFlags/Switzerland.png") },
  { name: "Syria", path: require("../worldFlags/Syria.png") },
  { name: "Taiwan", path: require("../worldFlags/Taiwan.png") },
  { name: "Tajikistan", path: require("../worldFlags/Tajikistan.png") },
  { name: "Tanzania", path: require("../worldFlags/Tanzania.png") },
  { name: "Thailand", path: require("../worldFlags/Thailand.png") },
  { name: "Togo", path: require("../worldFlags/Togo.png") },
  { name: "Tonga", path: require("../worldFlags/Tonga.png") },
  { name: "Trinidad and Tobago", path: require("../worldFlags/Trinidad_and_Tobago.png") },
  { name: "Tunisia", path: require("../worldFlags/Tunisia.png") },
  { name: "Turkey", path: require("../worldFlags/Turkey.png") },
  { name: "Turkmenistan", path: require("../worldFlags/Turkmenistan.png") },
  { name: "Tuvalu", path: require("../worldFlags/Tuvalu.png") },
  { name: "Uganda", path: require("../worldFlags/Uganda.png") },
  { name: "Ukraine", path: require("../worldFlags/Ukraine.png") },
  { name: "United Arab Emirates", path: require("../worldFlags/United_Arab_Emirates.png") },
  { name: "United Kingdom", path: require("../worldFlags/United_Kingdom.png") },
  { name: "United States", path: require("../worldFlags/United_States.png") },
  { name: "Uruguay", path: require("../worldFlags/Uruguay.png") },
  { name: "Uzbekistan", path: require("../worldFlags/Uzbekistan.png") },
  { name: "Vanuatu", path: require("../worldFlags/Vanuatu.png") },
  { name: "Vatican City", path: require("../worldFlags/Vatican_City.png") },
  { name: "Venezuela", path: require("../worldFlags/Venezuela.png") },
  { name: "Vietnam", path: require("../worldFlags/Vietnam.png") },
  { name: "Yemen", path: require("../worldFlags/Yemen.png") },
  { name: "Zambia", path: require("../worldFlags/Zambia.png") },
  { name: "Zimbabwe", path: require("../worldFlags/Zimbabwe.png") },
];
